import { createFileRoute, Link } from '@tanstack/react-router'
import { ArrowUpRight, ChevronRight, MapPin } from 'lucide-react'
import { DetailCard, SiteFooter, SiteHeader } from '@/components/site-chrome'
import { EditorialHero, KiezMarquee, StorySlider } from '@/components/editorial-hero'

export const Route = createFileRoute('/')({
  head: () => ({ meta: [{ title: 'Kuhnke Immobilien · Berlin mit Weitblick' }, { name: 'description', content: 'Kuhnke Immobilien begleitet Wohnimmobilien und Investment in Berlin und Umland – persönlich mit Marie Kuhnke.' }, { property: 'og:title', content: 'Kuhnke Immobilien · Berlin mit Weitblick' }, { property: 'og:description', content: 'Persönliche Immobilienberatung für Berlin und Umland.' }] }),
  component: HomePage,
})

const propertyTypes = [
  { slug: 'eigentumswohnungen', title: 'Eigentumswohnungen', text: 'Für Altbau, Neubau und alles dazwischen – mit einer Vermarktung, die den Charakter sichtbar macht.' },
  { slug: 'haeuser-grundstuecke', title: 'Häuser & Grundstücke', text: 'Ein- und Doppelhaushälften, Grundstücke und Orte, an denen der nächste Lebensabschnitt beginnt.' },
  { slug: 'entwicklungsgrundstuecke', title: 'Entwicklungsgrundstücke', text: 'Lage, Potenzial und Perspektive für Flächen mit einer klaren Idee.' },
  { slug: 'wohn-geschaeftshaeuser', title: 'Wohn- & Geschäftshäuser', text: 'Investment mit Blick auf Substanz, Nutzung und das, was langfristig trägt.' },
]

const journal = [
  { district: 'Charlottenburg', title: 'Charlottenburg zwischen Kurfürstendamm und Lietzensee', image: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=1200&q=85' },
  { district: 'Mitte', title: 'Mitte zwischen Geschichte und Gegenwart', image: 'https://images.unsplash.com/photo-1560969184-10fe8719e047?auto=format&fit=crop&w=1200&q=85' },
  { district: 'Schöneberg', title: 'Schöneberg als Lebensgefühl', image: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=85' },
]

function HomePage() {
  return <div className="min-h-dvh bg-background"><SiteHeader /><main>
    <EditorialHero />
    <KiezMarquee />
    <section className="border-b border-border bg-background"><div className="mx-auto grid max-w-[1440px] lg:grid-cols-[0.68fr_1.32fr]"><div className="border-b border-border px-5 py-16 sm:px-8 lg:border-b-0 lg:border-r lg:px-12 lg:py-24"><h2 className="font-serif text-4xl leading-tight sm:text-5xl">Der richtige Blick beginnt mit dem <em className="text-primary">richtigen</em> Zuhören.</h2></div><div className="grid sm:grid-cols-2">{propertyTypes.map((item) => <article key={item.slug} className="group border-b border-border p-6 transition hover:bg-muted sm:p-8 lg:p-10"><h3 className="max-w-[230px] font-serif text-2xl leading-tight">{item.title}</h3><p className="mt-4 max-w-xs text-sm leading-7 text-muted-foreground">{item.text}</p><Link to="/immobilien/$category" params={{ category: item.slug }} className="mt-8 inline-flex h-8 w-8 items-center justify-center text-primary transition hover:translate-x-1 hover:text-foreground" aria-label={`Mehr über ${item.title}`}><ChevronRight className="h-4 w-4" /></Link></article>)}</div></div></section>
    <StorySlider />
    <section className="mx-auto grid max-w-[1440px] gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[1.15fr_0.85fr] lg:gap-24 lg:px-12 lg:py-28"><div className="relative aspect-[4/5] max-h-[780px] overflow-hidden bg-muted"><img src="https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?auto=format&fit=crop&w=1400&q=85" alt="Helles Berliner Altbauzimmer als Portrait-Platzhalter" loading="lazy" className="h-full w-full object-cover" /><div className="absolute inset-4 border border-primary/60" /><span className="absolute bottom-0 left-0 right-0 bg-foreground/80 px-4 py-3 text-[0.62rem] uppercase tracking-[0.14em] text-background/80">Platzhalter · Portrait Marie Kuhnke</span></div><div className="flex flex-col justify-center"><h2 className="font-serif text-6xl leading-[0.9] tracking-[-0.05em] sm:text-7xl lg:text-[5.5rem]">Marie<br /><em className="text-primary">Kuhnke.</em></h2><p className="mt-8 max-w-md text-base leading-8 text-muted-foreground">„Ich glaube daran, dass gute Immobilienberatung nicht distanziert sein muss. Sie darf klar, aufmerksam und persönlich sein – und genau dort anfangen, wo Ihre Frage liegt.“</p><p className="mt-7 max-w-sm font-sans text-[0.65rem] uppercase leading-6 tracking-[0.14em] text-primary">Geschäftsführerin · §34c GewO<br />Im Vorstand des Immobilienverbandes Berlin und Brandenburg</p></div></section>
    <section className="bg-muted"><div className="mx-auto max-w-[1440px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="flex flex-col justify-between gap-8 sm:flex-row sm:items-end"><div><p className="eyebrow text-primary">Aus dem Kiez Atlas</p><h2 className="mt-5 max-w-xl font-serif text-4xl leading-tight sm:text-5xl">Berlin ist mehr als eine <em className="text-primary">Adresse.</em></h2></div><Link to="/kiez-wissen" className="inline-flex items-center gap-2 text-xs uppercase tracking-[0.14em] hover:text-primary">Alle Bezirke ansehen <ArrowUpRight className="h-4 w-4" /></Link></div><div className="mt-12 grid gap-5 md:grid-cols-3">{journal.map((item) => <Link key={item.title} to="/kiez-wissen" className="group block"><div className="relative aspect-[4/3] overflow-hidden"><img src={item.image} alt={`${item.district} – Bildplatzhalter`} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /><span className="absolute left-4 top-4 bg-background px-3 py-2 text-[0.6rem] uppercase tracking-[0.14em]">{item.district}</span></div><div className="flex items-start justify-between gap-4 border-b border-border py-5"><h3 className="max-w-xs font-serif text-2xl leading-tight group-hover:text-primary">{item.title}</h3><ArrowUpRight className="mt-1 h-4 w-4 shrink-0 text-primary" /></div></Link>)}</div></div></section>
    <section className="bg-foreground text-background"><div className="mx-auto grid max-w-[1440px] gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[0.7fr_1.3fr] lg:gap-24 lg:px-12 lg:py-28"><div><p className="eyebrow text-primary">Unsere Arbeitsweise</p><h2 className="mt-6 font-serif text-4xl leading-tight sm:text-5xl">Klar im Prozess.<br /><em className="text-primary">Nah am Menschen.</em></h2></div><div className="grid gap-8 sm:grid-cols-3"><DetailCard number="01" title="Lösungsorientiert" text="Wir sortieren, priorisieren und halten den nächsten sinnvollen Schritt sichtbar." /><DetailCard number="02" title="Zeitgemäß" text="Wir denken Vermarktung weiter – vom Exposé bis zum passenden digitalen Auftritt." /><DetailCard number="03" title="Persönlich" text="Marie bleibt Ihre Ansprechpartnerin: präsent, verbindlich und mit echtem Interesse." /></div></div></section>
    <section className="mx-auto grid max-w-[1440px] gap-8 px-5 py-16 sm:px-8 md:grid-cols-2 lg:px-12 lg:py-20"><Link to="/bewerten" className="group flex min-h-[230px] flex-col justify-between bg-primary p-7 text-primary-foreground transition hover:-translate-y-1 sm:p-10"><div className="flex items-start justify-between"><p className="eyebrow">Jetzt weitergehen</p><ArrowUpRight className="h-5 w-5" /></div><div><h2 className="font-serif text-4xl">Immobilie bewerten lassen</h2><p className="mt-3 max-w-sm text-sm leading-6 text-primary-foreground/75">Klicken Sie hier und erhalten Sie eine persönliche Preisspanne von Marie – unverbindlich und ohne automatische Standardantwort.</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em]">Zur Bewertung <ArrowUpRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></span></div></Link><Link to="/kiez-finder" className="group flex min-h-[230px] flex-col justify-between border border-primary bg-background p-7 transition hover:-translate-y-1 sm:p-10"><div className="flex items-start justify-between"><p className="eyebrow text-primary">Jetzt weitergehen</p><MapPin className="h-5 w-5 text-primary" /></div><div><h2 className="font-serif text-4xl">Meinen Kiez finden</h2><p className="mt-3 max-w-sm text-sm leading-6 text-muted-foreground">Klicken Sie hier, beantworten Sie fünf Fragen und entdecken Sie die Berliner Bezirke, die zu Ihnen passen.</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-primary">Zum Kiez-Finder <ArrowUpRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></span></div></Link></section>
    <section className="border-t border-border bg-muted"><div className="mx-auto grid max-w-[1440px] gap-8 px-5 py-16 sm:px-8 lg:grid-cols-[1fr_auto] lg:items-center lg:px-12 lg:py-20"><div><p className="eyebrow text-primary">Lassen Sie uns anfangen</p><h2 className="mt-5 max-w-2xl font-serif text-4xl leading-tight sm:text-5xl">Ihre Immobilie. Ihr Kiez. <em className="text-primary">Ihr nächster Schritt.</em></h2></div><Link to="/kontakt" className="button-gold inline-flex items-center justify-center gap-3 px-6 py-4 text-xs font-semibold uppercase tracking-[0.14em]">Kontakt aufnehmen <ArrowUpRight className="h-4 w-4" /></Link></div></section>
  </main><SiteFooter /></div>
}