/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberMarieRouteImport } from './routes/ueber-marie'
import { Route as ReferenzenRouteImport } from './routes/referenzen'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KiezWissenRouteImport } from './routes/kiez-wissen'
import { Route as KiezFinderRouteImport } from './routes/kiez-finder'
import { Route as ImmobilienRouteImport } from './routes/immobilien'
import { Route as BewertenRouteImport } from './routes/bewerten'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImmobilienIndexRouteImport } from './routes/immobilien.index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ImmobilienCategoryRouteImport } from './routes/immobilien.$category'

const UeberMarieRoute = UeberMarieRouteImport.update({
  id: '/ueber-marie',
  path: '/ueber-marie',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzenRoute = ReferenzenRouteImport.update({
  id: '/referenzen',
  path: '/referenzen',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KiezWissenRoute = KiezWissenRouteImport.update({
  id: '/kiez-wissen',
  path: '/kiez-wissen',
  getParentRoute: () => rootRouteImport,
} as any)
const KiezFinderRoute = KiezFinderRouteImport.update({
  id: '/kiez-finder',
  path: '/kiez-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmobilienRoute = ImmobilienRouteImport.update({
  id: '/immobilien',
  path: '/immobilien',
  getParentRoute: () => rootRouteImport,
} as any)
const BewertenRoute = BewertenRouteImport.update({
  id: '/bewerten',
  path: '/bewerten',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmobilienIndexRoute = ImmobilienIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImmobilienRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ImmobilienCategoryRoute = ImmobilienCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ImmobilienRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/bewerten': typeof BewertenRoute
  '/immobilien': typeof ImmobilienRouteWithChildren
  '/kiez-finder': typeof KiezFinderRoute
  '/kiez-wissen': typeof KiezWissenRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/referenzen': typeof ReferenzenRoute
  '/ueber-marie': typeof UeberMarieRoute
  '/immobilien/$category': typeof ImmobilienCategoryRoute
  '/app/': typeof AppIndexRoute
  '/immobilien/': typeof ImmobilienIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bewerten': typeof BewertenRoute
  '/kiez-finder': typeof KiezFinderRoute
  '/kiez-wissen': typeof KiezWissenRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/referenzen': typeof ReferenzenRoute
  '/ueber-marie': typeof UeberMarieRoute
  '/immobilien/$category': typeof ImmobilienCategoryRoute
  '/app': typeof AppIndexRoute
  '/immobilien': typeof ImmobilienIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/bewerten': typeof BewertenRoute
  '/immobilien': typeof ImmobilienRouteWithChildren
  '/kiez-finder': typeof KiezFinderRoute
  '/kiez-wissen': typeof KiezWissenRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/referenzen': typeof ReferenzenRoute
  '/ueber-marie': typeof UeberMarieRoute
  '/immobilien/$category': typeof ImmobilienCategoryRoute
  '/app/': typeof AppIndexRoute
  '/immobilien/': typeof ImmobilienIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/bewerten'
    | '/immobilien'
    | '/kiez-finder'
    | '/kiez-wissen'
    | '/kontakt'
    | '/leistungen'
    | '/referenzen'
    | '/ueber-marie'
    | '/immobilien/$category'
    | '/app/'
    | '/immobilien/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bewerten'
    | '/kiez-finder'
    | '/kiez-wissen'
    | '/kontakt'
    | '/leistungen'
    | '/referenzen'
    | '/ueber-marie'
    | '/immobilien/$category'
    | '/app'
    | '/immobilien'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/bewerten'
    | '/immobilien'
    | '/kiez-finder'
    | '/kiez-wissen'
    | '/kontakt'
    | '/leistungen'
    | '/referenzen'
    | '/ueber-marie'
    | '/immobilien/$category'
    | '/app/'
    | '/immobilien/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BewertenRoute: typeof BewertenRoute
  ImmobilienRoute: typeof ImmobilienRouteWithChildren
  KiezFinderRoute: typeof KiezFinderRoute
  KiezWissenRoute: typeof KiezWissenRoute
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRoute
  ReferenzenRoute: typeof ReferenzenRoute
  UeberMarieRoute: typeof UeberMarieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-marie': {
      id: '/ueber-marie'
      path: '/ueber-marie'
      fullPath: '/ueber-marie'
      preLoaderRoute: typeof UeberMarieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen': {
      id: '/referenzen'
      path: '/referenzen'
      fullPath: '/referenzen'
      preLoaderRoute: typeof ReferenzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiez-wissen': {
      id: '/kiez-wissen'
      path: '/kiez-wissen'
      fullPath: '/kiez-wissen'
      preLoaderRoute: typeof KiezWissenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiez-finder': {
      id: '/kiez-finder'
      path: '/kiez-finder'
      fullPath: '/kiez-finder'
      preLoaderRoute: typeof KiezFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immobilien': {
      id: '/immobilien'
      path: '/immobilien'
      fullPath: '/immobilien'
      preLoaderRoute: typeof ImmobilienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bewerten': {
      id: '/bewerten'
      path: '/bewerten'
      fullPath: '/bewerten'
      preLoaderRoute: typeof BewertenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immobilien/': {
      id: '/immobilien/'
      path: '/'
      fullPath: '/immobilien/'
      preLoaderRoute: typeof ImmobilienIndexRouteImport
      parentRoute: typeof ImmobilienRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/immobilien/$category': {
      id: '/immobilien/$category'
      path: '/$category'
      fullPath: '/immobilien/$category'
      preLoaderRoute: typeof ImmobilienCategoryRouteImport
      parentRoute: typeof ImmobilienRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ImmobilienRouteChildren {
  ImmobilienCategoryRoute: typeof ImmobilienCategoryRoute
  ImmobilienIndexRoute: typeof ImmobilienIndexRoute
}

const ImmobilienRouteChildren: ImmobilienRouteChildren = {
  ImmobilienCategoryRoute: ImmobilienCategoryRoute,
  ImmobilienIndexRoute: ImmobilienIndexRoute,
}

const ImmobilienRouteWithChildren = ImmobilienRoute._addFileChildren(
  ImmobilienRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BewertenRoute: BewertenRoute,
  ImmobilienRoute: ImmobilienRouteWithChildren,
  KiezFinderRoute: KiezFinderRoute,
  KiezWissenRoute: KiezWissenRoute,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRoute,
  ReferenzenRoute: ReferenzenRoute,
  UeberMarieRoute: UeberMarieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
